### ISSUE TITLE
Why ? "php": ">=7.0.0"

### ISSUE THREAD

**Issue by tarranjones** [roots/multisite-url-fixer#4]
Hi, 
is there a reason this requires php 7? 
If not would it be possible for you to lower the version in the composer.json file as i'm getting the following error.

` - roots/multisite-url-fixer 1.0.0 requires php >=7.0.0 -> your PHP version (5.6.14) does not satisfy that requirement.`

**Comment by retlehs** [comment]
is there a reason why you're using a version of PHP that isn't actively supported? :)

**Comment by QWp6t** [comment]
Add this to composer.json to tell Composer you're using PHP 7.0. I have no idea whether this will cause things to explode, however.

```
"config": {
    "platform": {
        "php": "7.0"
    }
}
```

**Comment by tarranjones** [comment]
@retlehs, I'm always switching between project, as long as i don't try to use php7 syntax this version suits me fine.
@QWp6t , Thanks i ended up using  `composer update roots/multisite-url-fixer --ignore-platform-reqs`
 I seems to work fine on 5.4,
