### ISSUE TITLE
URLs are not fixed for plugins and theme files

### ISSUE THREAD

**Issue by erralb** [roots/multisite-url-fixer#5]
Hi, maybe I got something wrong, but I thought the stylesheets and plugin files URLs would be fixed by your plugin.

But if you look at the source of this site : https://casas-turquesa.com/, you will see a lot of URLs like this : 
https://campo-de-arroz.com/app/plugins/contact-form-7/includes/css/styles.css?ver=5.0.2

https://campo-de-arroz.com being the main domain of the multisite.

Can you help? Did I do something wrong?

**Comment by JulienMelissas** [comment]
This plugin does not effect the paths for other stylesheets or plugins, just the URLs for sites using Bedrock, specifically to fix broken links with the `/wp/` that Bedrock adds due to WordPress being installed in a subfolder.

Going to close this one as it's not in the scope of the plugin.

**Comment by erralb** [comment]
I see! Thanks for your answer. 
Maybe it should be precised on your read me to avoid misunderstandings!

**Comment by JulienMelissas** [comment]
>Maybe it should be precised on your read me to avoid misunderstandings!

PR added for this here: #8
